### ISSUE TITLE
Quiz Lv2 Feedback

### ISSUE THREAD

**Issue by afiiif** [AbiyasaEka/nxn-level2-quiz#1]
Maaf baru sempat review.. 🙏  
Terima kasih buat submissionnya, jazakallaahu khoir.

Saya ada beberapa feedback:

**1.)**  
Komponennya baiknya dipisah2 saja..  
Saya lihat yg sekarang kan masih digabung semua spt ini,

```jsx
function App() {
  // ...

  const PageDisplay = () => { /* ... */ }
}

root.render(<App />);
```

Baiknya dipisah2, misal spt ini:

```jsx
function Page1() { /* ... */ }

function Page2() { /* ... */ }

function Page3() { /* ... */ }

function Page4() { /* ... */ }

function App() {
  // ...
  // <Page1 />
  // <Page2 />
  // ...
}

root.render(<App />);

```

**2.)**  
Set state seharusnya di dalam sebuah action atau di dalam `useEffect`, bukan langsung di component seperti ini:

```jsx
const [formData, setFormData] = React.useState(/* ... */);

if (formData.service === "") {
  setFormData({ ...formData, service: "Development" }); // ❌
}

useEffect(() => {
  setFormData(/* ... */); ✅
}, []);

return (
  <button
    onClick={() => {
      setFormData(/* ... */); ✅
    }}
  />
);
```

**3.)**  
Utk penggunaan `document.getElementById` bisa diganti dg memanfaatkan `useRef`.

```jsx
const inputRef = useRef();

return (
  <>
    <input ref={inputRef} />
    <button onClick={() => inputRef.focus() }>Focus</button>
  </>
);
```

.

Semoga dimudahkan, barokallaah

**Comment by afiiif** [comment]
Oiya, sama font-nya juga.  
Ketika dibuka di komputer yg tidak ada font "DM Sans" maka fontnya akan tidak sesuai.

Seharusnya diimport juga fontnya.  
Bisa import dr google fonts 💡

**Comment by AbiyasaEka** [comment]
Sudah ana revisi akh, mohon dicek lagi

**Comment by afiiif** [comment]
Sipp2, udah oke mas ✅
